export const SHOW_USER_VIEW = 'SHOW_USER_VIEW';
export const HIDE_USER_VIEW = 'HIDE_USER_VIEW';

export const GET_ALBUMS_PENDING = 'GET_ALBUMS_PENDING';
export const GET_ALBUMS_FULFILLED = 'GET_ALBUMS_FULFILLED';
export const GET_ALBUMS_REJECTED = 'GET_ALBUMS_REJECTED';
export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';

export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_FULFILLED = 'GET_PHOTOS_FULFILLED';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';
export const SET_CURRENT_PHOTO = 'SET_CURRENT_PHOTO';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';