export const GET_ALBUMS_PENDING = 'GET_ALBUMS_PENDING';
export const GET_ALBUMS_FULFILLED = 'GET_ALBUMS_FULFILLED';
export const GET_ALBUMS_REJECTED = 'GET_ALBUMS_REJECTED';

export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_FULFILLED = 'GET_PHOTOS_FULFILLED';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';